name: janky-calibrate
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pyqt
  - opencv
  - imageio
  - imageio-ffmpeg
  - ffmpeg
  - matplotlib
  - sleap-io
  - pygfx
  - attrs
  - pip
  - pip:
    - -e .
